version: '3.8'

services:
  db:
    image: postgres:10
    container_name: dev_mem_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev_mem
    ports:
      - "45533:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
