version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      JDBC_URL: ${jdbcUrl}
      JDBC_USER: ${dbUser}
      JDBC_PASSWORD: ${dbPassword}
    depends_on:
      - postgres
  postgres:
    image: postgres:9.4
    environment:
      POSTGRES_DB: dev_mem
      POSTGRES_USER: ${dbUser}
      POSTGRES_PASSWORD: ${dbPassword}
    ports:
      - '45533:5432'