version: "3.9"
services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: "dev_mem"
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
    ports:
      - "45533:5432"